### ISSUE TITLE
ori_inds = ori_inds[~too_small] RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by wei3044** [lx-cly/YOLOv7_OBB#13]
请问大家这个问题怎么解决
![image](https://github.com/lx-cly/YOLOv7_OBB/assets/59051955/ae65d2f5-6b18-4498-bec3-d81c0fe25d70)

**Comment by jaydeboer** [comment]
I am curious how you solved this. I am facing the same problem and could use some direction.

**Comment by ali0625** [comment]
> I am curious how you solved this. I am facing the same problem and could use some direction.

You can change nms_rotated_wrapper.py ori_inds = torch.arange(dets_th.size(0)) # 0 ~ n-1
to ori_inds = torch.arange(dets_th.size(0)).to('cuda') # 0 ~ n-1
