### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by hecheng000** [lx-cly/YOLOv7_OBB#20]
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by liuzhan123456** [comment]
我也是这个问题，请问您解决了吗

**Comment by lx-cly** [comment]
`ValueError: not enough values to unpack (expected 3, got 0)` 就是你的cache文件中，没有一个有效标签。检查数据，查看生成cache时候打印的`WARNING: Ignoring corrupted image and/or label`警告提示。

**Comment by hecheng000** [comment]
还是不清楚咋解决啊好兄弟
















在 2023-11-07 17:25:11，"lx-cly" ***@***.***> 写道：

ValueError: not enough values to unpack (expected 3, got 0) 就是你的cache文件中，没有一个有效标签。检查数据，查看生成cache时候打印的WARNING: Ignoring corrupted image and/or label警告提示。
