### ISSUE TITLE
opencv版本问题

### ISSUE THREAD

**Issue by iodncookie** [lx-cly/YOLOv7_OBB#9]
https://github.com/lx-cly/YOLOv7_OBB/blob/2ee2392f00ab7cc36dbf69597114c4be81b84612/requirements.txt#L6

大佬，opencv-4.2和opencv-4.5+版本关于角度定义是不同的，想问一下这个应该用哪个版本适合？

**Comment by lx-cly** [comment]
opencv-4.5+版本
